name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  browser_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [25.x]
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/setup-env
        with:
            node-version: ${{ matrix.node-version }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build the React app
        run: npm run build --if-present

      - name: Run the browser tests
        run: npm run test:browser

  node_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [25.x]
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/setup-env
        with:
            node-version: ${{ matrix.node-version }}

      - name: Run the node tests
        run: npm run test:node
