name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'Bug/*'
      - 'Feature/*'
      - 'Test/*'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [25.x]
    steps:
      - uses: actions/checkout@v4
      - run: echo Setting up Node.js...
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo Installing npm packages...
      - run: npm ci
      - run: echo Installing Playwright browsers...
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - run: echo Building the app...
      - name: Build the React app
        run: npm run build --if-present
      - run: echo Running the tests...
      - name: Run the Vitest tests
        run: npm test
